### ISSUE TITLE
Optimization compile error

### ISSUE THREAD

**Issue by gordonwatts** [gordonwatts/LINQtoROOT#140]
Looks like these aren't all fixed yet.
Comes from a full run of TrainingTestResults.

    Warning in <TROOT::Append>: Replacing existing TH1: weightAll (Potential memory leak).
    Info in <TWinNTSystem::ACLiC>: creating shared library C:\Users\gordo\AppData\Local\Temp\LINQToTTree\TrainingTestResults\azske5qj.fku\query0_cxx.dll
    2548857_cint.cxx
    query0_cxx_ACLiC_dict.cxx
    C:\Users\gordo\AppData\Local\Temp\LINQToTTree\TrainingTestResults\azske5qj.fku\query0.cxx(354) : error C2065: 'aInt32_1847' : undeclared identifier
    Error in <ACLiC>: Compilation failed!

    Unhandled Exception: System.InvalidOperationException: Failed to compile 'C:\Users\gordo\AppData\Local\Temp\LINQToTTree\TrainingTestResults\azske5qj.fku\query0.cxx' - This is a very bad internal error - inspect the file to see if you can see what went wrong and report!!!
       at LINQToTTreeLib.ExecutionCommon.LocalExecutor.CompileAndLoad(FileInfo templateRunner)
       at LINQToTTreeLib.ExecutionCommon.LocalExecutor.Execute(FileInfo templateFile, DirectoryInfo queryDirectory, IEnumerable`1 varsToTransfer)
       at LINQToTTreeLib.TTreeQueryExecutor.ExecuteQueuedQueries()
       at LINQToTTreeLib.FutureValue`1.get_Value()
       at LINQToTTreeLib.TTreeQueryExecutor.CloneFutureValue`1.get_Value()
       at LINQToTTreeLib.TTreeQueryExecutor.AddedFutureValue`1.get_Value()
       at LINQToTTreeLib.TTreeQueryExecutor.AddedFutureValue`1.get_Value()
       at LINQToTTreeLib.TTreeQueryExecutor.AddedFutureValue`1.get_Value()
       at LINQToTTreeLib.TTreeQueryExecutor.AddedFutureValue`1.get_Value()
       at LINQToTTreeLib.TTreeQueryExecutor.AddedFutureValue`1.get_Value()
       at LINQToTreeHelpers.FutureUtils.Operators.<>c__DisplayClass27_0`2.<ExtractValue>b__0()
       at LINQToTreeHelpers.FutureUtils.Operators.DoFutureOperator`1.get_Value()
       at TrainingTestResults.Program.PlotMVAResult(IQueryable`1 source, FutureTDirectory dir, Expression`1 mvaValue) in C:\Users\gordo\Documents\Code\calratio2015\JetCutStudies\TrainingTestResults\Program.cs:line 125
       at TrainingTestResults.Program.Main(String[] args) in C:\Users\gordo\Documents\Code\calratio2015\JetCutStudies\TrainingTestResults\Program.cs:line 80

**Comment by gordonwatts** [comment]
[query0.txt](https://github.com/gordonwatts/LINQtoROOT/files/347576/query0.txt)

**Comment by gordonwatts** [comment]
[query0-non-opt.txt](https://github.com/gordonwatts/LINQtoROOT/files/347585/query0-non-opt.txt)

Here is a non-optimized version of the same query

**Comment by gordonwatts** [comment]
The code that is having trouble here is a conditional. When we write a conditional out, we do the if part of the conditional in an assign statement. This seems to be the bit that has broken. Either it wasn't "re-assigned" or some other variable wasn't re-assigned.

**Comment by gordonwatts** [comment]
so 3961 is the aInt32 having trouble now. And what is missing is the declaration.
That means:

   1. It was in a code block that was removed, and this statement was somehow moved here without the decl.
   1. The decl was force moved for some reason.

**Comment by gordonwatts** [comment]
The bug is "simple" (not sure how to fix it yet):

                foreach (var item in renames)
                {
                    opt.ForceRemoveDeclaration(item.Item1, s2Parent);
                    opt.ForceRenameVariable(item.Item1, item.Item2);
                }

the problem is that the opt is attached to a block below where the variable in item1 is declared. As a result, it isn't renamed... but since the "force" remove above will walk back up the tree, the decl is removed.
So the ForceRename has to be more cleaver - it has to start the rename from the block we removed it from.
