### ISSUE TITLE
as_array sometimes access violates

### ISSUE THREAD

**Issue by gordonwatts** [gordonwatts/LINQtoROOT#156]
Here is a typical type of crash:

    17:45:43 Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
    17:45:43    at ROOTNET.Utility.CPPArraychar.as_array(Int32 array_size)
    17:45:43    at LINQToTTreeLib.Utils.ObjectHashCalculator.InternalAccumulateHash(NTObject nTObject)
    17:45:43    at LINQToTTreeLib.Utils.ObjectHashCalculator.InternalAccumulateNamedHash(NTNamed namedObj)
    17:45:43    at LINQToTTreeLib.Utils.ObjectHashCalculator.AccumutlateHash(Object o)
    17:45:43    at LINQToTTreeLib.QueryResultCache.CalcObjectHash(Object[] inputObjects)
    17:45:43    at LINQToTTreeLib.QueryResultCache.GetKey(Uri[] unsortedRootfiles, String treename, Object[] inputObjects, String[] unsortedCrumbs, QueryModel query, Boolean recheckDates)
    17:45:43    at LINQToTTreeLib.TTreeQueryExecutor.ExecuteScalarAsFuture[TResult](QueryModel queryModel)
    17:45:43    at LINQToTTreeLib.TTreeQueryExecutor.ExecuteUnknownQM[TResult](QueryModel q)
    17:45:43    at LINQToTTreeLib.TTreeQueryExecutor.<ExecuteScalarConcatQM>b__27_0[TResult](QueryModel q)
    17:45:43    at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
    17:45:43    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
    17:45:43    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
    17:45:43    at LINQToTTreeLib.TTreeQueryExecutor.ExecuteScalarConcatQM[TResult](QueryModel queryModel)
    17:45:43    at LINQToTTreeLib.TTreeQueryExecutor.ExecuteScalarAsFuture[TResult](QueryModel queryModel)
    17:45:43    at LINQToTTreeLib.FutureResultOperators.FutureExecuteScalarHelper[TSource,TResult](QueriableTTree`1 q, MethodCallExpression expr)
    17:45:43    at LINQToTTreeLib.FutureResultOperators.FutureAggregate[TSource,TAccumulate](IQueryable`1 source, TAccumulate seed, Expression`1 func)
    17:45:43    at LINQToTTreeLib.Helpers.FutureApplyToObject[TSource,TResult](IQueryable`1 source, TResult seed, Expression`1 apply)
    17:45:43    at LINQToTreeHelpers.Plotting.FuturePlot[TSource](IQueryable`1 source, String plotName, String plotTitle, Int32 nbins, Double lowBin, Double highBin, Expression`1 xValue, Expression`1 weight)
    17:45:43    at LINQToTreeHelpers.PlottingUtils.PlotSpec1D`1.MakeFuturePlot(String nameString, String titleString, IQueryable`1 goodEvents)
    17:45:43    at LINQToTreeHelpers.PlottingUtils.FuturePlot[T](IQueryable`1 sourceWithWeights, String name, String title, IPlotSpec`1 plotSpecification, String[] nameAndTitleFormatArgs)
    17:45:43    at TrainingTestResults.Program.PlotMVAResult(IQueryable`1 source, FutureTDirectory dir, Expression`1 mvaValue) in c:\jenkins\slave01\workspace\CalRatio2016\TrainingResults\TrainingTestResults\Program.cs:line 101
    17:45:43    at TrainingTestResults.Program.Main(String[] args) in c:\jenkins\slave01\workspace\CalRatio2016\TrainingResults\TrainingTestResults\Program.cs:line 75

**Comment by gordonwatts** [comment]
Not at all clear why this happens - but happens after a lot of activity. Here is where I pulled this from - 1000's of calls to this must have occurred before this happened....

http://higgs.phys.washington.edu:8080/job/CalRatio2016/job/TrainingResults/12/console

**Comment by gordonwatts** [comment]
Took a while to get Jenkins properly uploading things again, but now that that is working... the job seems to be running longer than it has before. Will have to wait a while to see if this works.

Also, it could be there was a bit of a performance hit due to this change. Lots more moving between the C++ and the .NET world.
