### ISSUE TITLE
Access Violation during TH1F clean up

### ISSUE THREAD

**Issue by gordonwatts** [gordonwatts/LINQtoROOT#168]
This is a hard one:

    Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
       at ROOTNET.NTH1F.DeleteHeldObject()
       at ROOTNET.Utility.ROOTDOTNETBaseTObject.!ROOTDOTNETBaseTObject()
       at ROOTNET.Utility.ROOTDOTNETBaseTObject.Dispose(Boolean A_0)
       at ROOTNET.Utility.ROOTDOTNETBaseTObject.Finalize()

It happens during GC cleanup:

    J10Z
    Warning in <TROOT::Append>: Replacing existing TH1: pTall (Potential memory leak).

    Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
       at ROOTNET.NTH1F.DeleteHeldObject()
       at ROOTNET.Utility.ROOTDOTNETBaseTObject.!ROOTDOTNETBaseTObject()
       at ROOTNET.Utility.ROOTDOTNETBaseTObject.Dispose(Boolean A_0)
       at ROOTNET.Utility.ROOTDOTNETBaseTObject.Finalize()
    Warning in <TROOT::Append>: Replacing existing TH1: etaall (Potential memory leak).
    Warning in <TROOT::Append>: Replacing existing TH1: phiall (Potential memory leak).
    Warning in <TROOT::Append>: Replacing existing TH1: CalRall (Potential memory leak).
    Warning in <TROOT::Append>: Replacing existing TH1: ntracksall (Potential memory leak).

And even during the crash, other threads are busy running and producing things (as you can see from the error messages above).

ROOT dumps a C++ stack trace as well. Here is what i could find:

    ================ Thread 5 ================
      libCore!THashList::RecursiveRemove()
      libCore!THashList::RecursiveRemove()
      libCore!TList::RecursiveRemove()
      libCore!THashList::RecursiveRemove()
      libCore!TObject::~TObject()
      libHist!TH1::~TH1()
      libHist!TH1F::~TH1F()
      libHist!std::_Vector_iterator<std::_Vector_val<std::_Simple_types<std::pair<double,double> > > >::operator-=()
      0xbafc067 ??
      0xb28adc8 ??
      0xb28ad71 ??
      0xb28ad3c ??
      clr!CreateApplicationContext()
      clr!CreateApplicationContext()
      clr!CreateApplicationContext()
      clr!CreateApplicationContext()
      clr!CreateApplicationContext()
      clr!DllUnregisterServerInternal()
      clr!DllUnregisterServerInternal()
      clr!DllUnregisterServerInternal()
      clr!CreateApplicationContext()
      clr!CreateApplicationContext()
      clr!LogHelp_TerminateOnAssert()
      KERNEL32!BaseThreadInitThunk()
      ntdll!RtlGetAppContainerNamedObjectPath()
      ntdll!RtlGetAppContainerNamedObjectPath()

**Comment by gordonwatts** [comment]
The interesting aspect of this is: is this a multi-threaded problem?

- From the messages that are being printed out clearly the code proceeds after the crash
- Using GC.Collect() to force the garbage collector to clean up everything... and crash should happen during that. This is an attempt to localize the problem.
- But it should wait until all finalizers have completed.

From the manual on GC.Collect:
    Use this method to try to reclaim all memory that is inaccessible. It performs a blocking garbage collection of all generations. 

The real question: is this due to our code continuing and doing something during Finalizer running, or is this due to a bug in how we track ROOT objects, and would happen even in totally single threaded mode?

There is the WaitForPendingFinalizers() method - that should clean up some of the contention.

And it works. So if I take that at face value, this is a thread contention problem! Need a lock on the finalizer thread to prevent the main thread from continuing to run! Super ugh!

Lets make the test bigger.

**Comment by gordonwatts** [comment]
Going the collection and other things (see next post) have dramatically improved things. But they still run into trouble if we do enough plots. The more common one I'm seeing now is:

    ================ Thread 2 ================
      libCore!THashList::RecursiveRemove()
      libCore!TObject::~TObject()
      libRIO!TDirectoryFile::~TDirectoryFile()
      libRIO!TFile::~TFile()
      libRIO!TString::operator+=()
      0xab7b007 ??
      0xab7adc8 ??
      0xab7ad71 ??
      0xab7ad3c ??
      clr!CreateApplicationContext()
      clr!CreateApplicationContext()
      clr!CreateApplicationContext()
      clr!CreateApplicationContext()
      clr!CreateApplicationContext()
      clr!DllUnregisterServerInternal()
      clr!DllUnregisterServerInternal()
      clr!DllUnregisterServerInternal()
      clr!CreateApplicationContext()
      clr!CreateApplicationContext()
      clr!LogHelp_TerminateOnAssert()
      KERNEL32!BaseThreadInitThunk()
      ntdll!RtlGetAppContainerNamedObjectPath()
      ntdll!RtlGetAppContainerNamedObjectPath()

**Comment by gordonwatts** [comment]
The following code really helped things out:

        /// <summary>
        /// Run an action with the GC suppressed (as much as it can)
        /// </summary>
        /// <remarks>
        /// This is done because there is a bug in an interaction between ROOT and the GC. Finalizers are were
        /// most objects are deleted. But if on the main thread something is being created at the same time, you
        /// can run into a race condition. Turnning off the GC temporarily suppresses the running of the Finalizers
        /// for a short while - as long as memory allocation doesn't get out of hand. When this bug is actually fixed
        /// we might be ok to remove this.
        /// 
        /// Might need to wait until ROOT v6 before that is the case.
        /// </remarks>
        /// <param name="noGCBuffer"></param>
        /// <param name="a"></param>
        private static void NoGCExecute (Action a)
        {
            GC.Collect();
            GC.WaitForPendingFinalizers();

            var oldMode = System.Runtime.GCSettings.LatencyMode;
            try
            {
                System.Runtime.GCSettings.LatencyMode = System.Runtime.GCLatencyMode.SustainedLowLatency;
                a();
            } finally
            {
                System.Runtime.GCSettings.LatencyMode = oldMode;
            }

            GC.Collect();
            GC.WaitForPendingFinalizers();
        }

**Comment by gordonwatts** [comment]
Perhaps the problem are the finalizers... they don't run blocked. Is deleting a root object thread safe? Especially if it removes itself from some sort of global catalog?
