### ISSUE TITLE
When making an SSH connection to a remote host, re-try.

### ISSUE THREAD

**Issue by gordonwatts** [gordonwatts/LINQtoROOT#229]
SSHConnectFailureException - is what we need to catch in the make connection code.

**Comment by gordonwatts** [comment]
LINQToTTreeLib.ExecutionCommon.RemoteBashExecutor.RemoteBashCommandFailureException occurred
  HResult=0x80131500
  Message=Error making a SSH connection: 
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at LINQToTTreeLib.ExecutionCommon.RemoteBashExecutor.MakeSSHConnection(Action`1 dumpLine)
   at LINQToTTreeLib.ExecutionCommon.RemoteBashExecutor.ExecuteRemoteWithTemp[T](String phase, Func`2 act, Action`1 dumpLine)
   at LINQToTTreeLib.ExecutionCommon.RemoteBashExecutor.ExecuteRootScript(String prefix, String cmds, DirectoryInfo tmpDir, Action`1 dumpLine, Boolean verbose, IEnumerable`1 extraFiles, IEnumerable`1 receiveFiles, Nullable`1 timeout)
   at LINQToTTreeLib.ExecutionCommon.RemoteBashExecutor.CheckForROOTInstall(Action`1 dumpLine, Boolean verbose)
   at LINQToTTreeLib.ExecutionCommon.CommandLineCommonExecutor.MakeSureROOTIsInstalled(Action`1 dumpLine, Boolean verbose)
   at LINQToTTreeLib.ExecutionCommon.CommandLineCommonExecutor.GenerateProxyFile(Uri[] rootFiles, String treeName, DirectoryInfo queryDirectory)
   at LINQToTTreeLib.TTreeQueryExecutor.ExecuteQueuedQueries()
   at LINQToTTreeLib.FutureValue`1.get_Value()
   at LINQToTTreeLib.TTreeQueryExecutor.ExecuteScalar[T](QueryModel queryModel)
   at Remotion.Linq.Clauses.StreamedData.StreamedScalarValueInfo.ExecuteScalarQueryModel[T](QueryModel queryModel, IQueryExecutor executor) in c:\Users\Gordon\Documents\Code\root\Relinq\Core\Clauses\StreamedData\StreamedScalarValueInfo.cs:line 65
   at Remotion.Linq.Clauses.StreamedData.StreamedScalarValueInfo.ExecuteQueryModel(QueryModel queryModel, IQueryExecutor executor) in c:\Users\Gordon\Documents\Code\root\Relinq\Core\Clauses\StreamedData\StreamedScalarValueInfo.cs:line 49
   at Remotion.Linq.QueryModel.Execute(IQueryExecutor executor) in c:\Users\Gordon\Documents\Code\root\Relinq\Core\QueryModel.cs:line 345
   at Remotion.Linq.QueryProviderBase.Execute(Expression expression) in c:\Users\Gordon\Documents\Code\root\Relinq\Core\QueryProviderBase.cs:line 123
   at Remotion.Linq.QueryProviderBase.System.Linq.IQueryProvider.Execute[TResult](Expression expression) in c:\Users\Gordon\Documents\Code\root\Relinq\Core\QueryProviderBase.cs:line 144
   at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
   at JetMVAClassifierTraining.Program.<>c__DisplayClass2_1.<GetBIBSamples>b__0(SampleMetaData s) in C:\Users\Gordon\Documents\Code\calratio2017\JetCutStudies\JetMVAClassifierTraining\Program.cs:line 336
   at System.Linq.Enumerable.<TakeWhileIterator>d__27`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at JetMVAClassifierTraining.Program.GetBIBSamples(Int32 requestedNumberOfEvents, DataEpoc epoc, Double pTCut, String[] avoidPlaces) in C:\Users\Gordon\Documents\Code\calratio2017\JetCutStudies\JetMVAClassifierTraining\Program.cs:line 327
   at JetMVAClassifierTraining.Program.Main(String[] args) in C:\Users\Gordon\Documents\Code\calratio2017\JetCutStudies\JetMVAClassifierTraining\Program.cs:line 100

Inner Exception 1:
SSHConnectFailureException: Unable to make the connection to tev01.phys.washington.edu.

Inner Exception 2:
SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
