### ISSUE TITLE
Re-try file read errors

### ISSUE THREAD

**Issue by gordonwatts** [gordonwatts/LINQtoROOT#230]
The following error happens once in a while when running across shares.
  
    C:\Users\gwatts\AppData\Local\Temp\LINQToTTree\JetMVAClassifierTraining\2wp304z3.exn\query43_cxx.lib and object C:\Users\gwatts\AppData\Local\Temp\LINQToTTree\JetMVAClassifierTraining\2wp304z3.exn\query43_cxx.exp
    23:17:39 Starting run...
    23:17:39 SysError in <TFile::ReadBuffer>: error reading from file \\samba.phys.washington.edu\tev-scratch4\users\gwatts\GRIDDS\user.gwatts.361026.Pythia8EvtGen_A14NNPDF23LO_jetjet_JZ6W.DAOD_EXOT15.p2649.DiVertAnalysis_v201_7EB0B08D_DB5BDB9D_hist\copied\user.gwatts.12083372._000018.hist-output.root (Invalid argument)
    23:17:39 Error in <TBranchElement::GetBasket>: File: \\samba.phys.washington.edu\tev-scratch4\users\gwatts\GRIDDS\user.gwatts.361026.Pythia8EvtGen_A14NNPDF23LO_jetjet_JZ6W.DAOD_EXOT15.p2649.DiVertAnalysis_v201_7EB0B08D_DB5BDB9D_hist\copied\user.gwatts.12083372._000018.hist-output.root at byte:119631189, branch:CalibJet_eta, entry:57378, badread=1, nerrors=1, basketnumber=160
    23:17:39 
    23:17:39    at LINQToTTreeLib.ExecutionCommon.CommandLineCommonExecutor.ExecuteRootScript(String prefix, String cmds, DirectoryInfo tmpDir, Action`1 dumpLine, Boolean verbose, IEnumerable`1 extraFiles, IEnumerable`1 fetchFiles, Nullable`1 timeout)
    23:17:39    at LINQToTTreeLib.ExecutionCommon.CommandLineCommonExecutor.Execute(FileInfo queryFile, DirectoryInfo queryDirectory, IEnumerable`1 varsToTransfer)

This is common enough (I've probably seen about 5 or 6 of these - especially when running the generic plotter) that we should put in a re-try. But lets make it limited - say 3 times.

We are effectively working around some sort of network/OS bug here.

**Comment by gordonwatts** [comment]
Left off the top part of this:

    23:17:39 Unhandled Exception: LINQToTTreeLib.ExecutionCommon.CommandLineCommonExecutor+CommandLineExecutionException: Failed to execute step Query - process executed with error code 255. Text dump from process: 
    23:17:39 Processing C:\Users\gwatts\AppData\Local\Temp\LINQToTTree\JetMVAClassifierTraining\2wp304z3.exn\Query.C...
    23:17:39 Info in <TWinNTSystem::ACLiC>: creating shared library C:\Users\gwatts\AppData\Local\Temp\LINQToTTree\JetMVAClassifierTraining\2wp304z3.exn\query43_cxx.dll
    23:17:39 25568101_cint.cxx
