### ISSUE TITLE
Too long Uri can cause crash

### ISSUE THREAD

**Issue by gordonwatts** [gordonwatts/LINQtoROOT#244]
System.IO.PathTooLongException occurred
      HResult=0x800700CE
      Message=The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
      Source=<Cannot evaluate the exception source>
      StackTrace:
       at System.IO.PathHelper.GetFullPathName()
       at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
       at System.IO.Path.GetFullPathInternal(String path)
       at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
       at System.IO.FileInfo..ctor(String fileName)
       at LINQToTTreeLib.QueryResultCache.GetKey(Uri[] unsortedRootfiles, String treename, Object[] inputObjects, String[] unsortedCrumbs, QueryModel query, Boolean recheckDates, Func`2 dateChecker)
       at LINQToTTreeLib.TTreeQueryExecutor.ExecuteScalarAsFuture[TResult](QueryModel queryModel)
       at LINQToTTreeLib.TTreeQueryExecutor.ExecuteScalar[T](QueryModel queryModel)
       at Remotion.Linq.Clauses.StreamedData.StreamedScalarValueInfo.ExecuteScalarQueryModel[T](QueryModel queryModel, IQueryExecutor executor) in c:\Users\Gordon\Documents\Code\root\Relinq\Core\Clauses\StreamedData\StreamedScalarValueInfo.cs:line 65
       at Remotion.Linq.Clauses.StreamedData.StreamedScalarValueInfo.ExecuteQueryModel(QueryModel queryModel, IQueryExecutor executor) in c:\Users\Gordon\Documents\Code\root\Relinq\Core\Clauses\StreamedData\StreamedScalarValueInfo.cs:line 49
       at Remotion.Linq.QueryModel.Execute(IQueryExecutor executor) in c:\Users\Gordon\Documents\Code\root\Relinq\Core\QueryModel.cs:line 345
       at Remotion.Linq.QueryProviderBase.Execute(Expression expression) in c:\Users\Gordon\Documents\Code\root\Relinq\Core\QueryProviderBase.cs:line 123
       at Remotion.Linq.QueryProviderBase.System.Linq.IQueryProvider.Execute[TResult](Expression expression) in c:\Users\Gordon\Documents\Code\root\Relinq\Core\QueryProviderBase.cs:line 144
       at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
       at libDataAccess.Files.GetSampleAsMetaData(String sample, Boolean weightByCrossSection, String[] avoidPlaces, Nullable`1 nfiles) in C:\Users\gordo\Documents\Code\calratio2017\JetCutStudies\libDataAccess\Files.cs:line 108
       at libDataAccess.Files.<>c__DisplayClass14_0`1.<TakeEventsFromSamlesEvenly>g__get_sample0(SampleMetaData sample) in C:\Users\gordo\Documents\Code\calratio2017\JetCutStudies\libDataAccess\Files.cs:line 221
       at libDataAccess.Files.<>c__DisplayClass14_0`1.<TakeEventsFromSamlesEvenly>b__3(SampleMetaData s) in C:\Users\gordo\Documents\Code\calratio2017\JetCutStudies\libDataAccess\Files.cs:line 235
       at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
       at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
       at libDataAccess.Files.TakeEventsFromSamlesEvenly[T](IEnumerable`1 dataSamples, Int32 numberOfEvents, Int32 numberOfFiles, Func`2 sampleConverter) in C:\Users\gordo\Documents\Code\calratio2017\JetCutStudies\libDataAccess\Files.cs:line 234
       at JetMVAClassifierTraining.Program.Main(String[] args) in C:\Users\gordo\Documents\Code\calratio2017\JetCutStudies\JetMVAClassifierTraining\Program.cs:line 85

**Comment by gordonwatts** [comment]
The file it was trying to open:

 	mscorlib.dll!System.IO.FileInfo.Init(string fileName = "C:\\Users\\gordo\\AppData\\Local\\LINQToTTree\\QueryCache\\-102917411 - recoTree-mc15_13TeV_304810_MadGraphPythia8EvtGen_A14NNPDF23LO_HSS_LLP_mH400_mS50_lt5m_merge_DAOD_EXOT15_e5102_s2698_r7772_r7676_p2877_nFiles=1\\\\query 588937867-inp-2128831035-crm757602046_%%CYCLE%%.root", bool checkHost) Line 102	C#	Symbols loaded.

**Comment by gordonwatts** [comment]
Fixed, and pushed, but somehow I forgot the change here!
