### ISSUE TITLE
Crash during a rename operation

### ISSUE THREAD

**Issue by gordonwatts** [gordonwatts/LINQtoROOT#259]
Seen in the wild:

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.FileInfo.MoveTo(String destFileName)
   at LINQToTTreeLib.Files.OutputTextFileTypeSaver.RenameForQueryCycle(IDeclaredParameter iVariable, NTObject[] obj, Int32 cycle)
   at LINQToTTreeLib.TTreeQueryExecutor.RenameForCycle[T](IDeclaredParameter iVariable, IDictionary`2 result, Int32 cycle)
   at LINQToTTreeLib.TTreeQueryExecutor.QueuedQuery`1.RenameForCycle(IDictionary`2 result, Int32 cycle)
   at LINQToTTreeLib.TTreeQueryExecutor.<ExecuteQueuedQueriesForAScheme>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LINQToTTreeLib.TTreeQueryExecutor.<ExecuteQueuedQueries>d__59.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at LINQToTreeHelpers.FutureUtils.FutureTDirectory.Write(Boolean calculateEverything)
   at LINQToTreeHelpers.FutureUtils.FutureTFile.Close()
   at LINQToTreeHelpers.FutureUtils.FutureTFile.Dispose()
   at MVADumpTrainingTuples.Program.<Main>d__1.MoveNext() in C:\Users\gordo\Documents\Code\calratio2017\JetCutStudies\MVADumpTrainingTuples\Program.cs:line 140
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MVADumpTrainingTuples.Program.<Main>(String[] args)

**Comment by gordonwatts** [comment]
This is probably a multi-threaded problem. :(

**Comment by gordonwatts** [comment]
Same as #261
