### ISSUE TITLE
ToCSV can't survive multi-threaded calls

### ISSUE THREAD

**Issue by gordonwatts** [gordonwatts/LINQtoROOT#261]
Run multiple ToCSV at the same time such that the queries are identical, then all copy back to the same file, and that means they can step on each other.

- Files the get copied back should either be copied back to a unique name or should come back and get renamed before anyone else has a chance to overwrite them.

Creating a test for this will be hard.

**Comment by gordonwatts** [comment]
The problem looks like it isn't quite above. Here is a crash dump from a rerpo in the wild:
```
Fetching HSS Sample
Fetching JZ Sample
Fetching BIB15 Sample
Fetching BIB16 Sample
Writing out csv files for signal.
LINTToTTreeLib Start: 30 : LINQToTTree Executor: running 1 queries on gridds://mc15_13tev/mc15_13TeV.304820.MadGraphPythia8EvtGen_A14NNPDF23LO_HSS_LLP_mH1000_mS400_lt5m.merge.DAOD_EXOT15.e5102_s2698_r7772_r7676_p2877?preferPlaces=UWTeV-linux,CERNLLP-linux&nFiles=2&jobName=DiVertAnalysis&jobVersion=201
LINTToTTreeLib Start: 13 : ExecuteQueuedQueriesForAScheme: Start run on Uri scheme remotebash, 1 files.
LINTToTTreeLib Stop: 13 : ExecuteQueuedQueriesForAScheme: Finished run on Uri scheme remotebash.
LINTToTTreeLib Stop: 30 : LINQToTTree Executor: finishnig query on gridds://mc15_13tev/mc15_13TeV.304820.MadGraphPythia8EvtGen_A14NNPDF23LO_HSS_LLP_mH1000_mS400_lt5m.merge.DAOD_EXOT15.e5102_s2698_r7772_r7676_p2877?preferPlaces=UWTeV-linux,CERNLLP-linux&nFiles=2&jobName=DiVertAnalysis&jobVersion=201
LINTToTTreeLib Start: 30 : LINQToTTree Executor: running 1 queries on gridds://mc15_13tev/mc15_13TeV.304819.MadGraphPythia8EvtGen_A14NNPDF23LO_HSS_LLP_mH1000_mS150_lt5m.merge.DAOD_EXOT15.e5102_s2698_r7772_r7676_p2877?preferPlaces=UWTeV-linux,CERNLLP-linux&nFiles=2&jobName=DiVertAnalysis&jobVersion=201
LINTToTTreeLib Start: 13 : ExecuteQueuedQueriesForAScheme: Start run on Uri scheme remotebash, 2 files.
LINTToTTreeLib Stop: 13 : ExecuteQueuedQueriesForAScheme: Finished run on Uri scheme remotebash.
LINTToTTreeLib Stop: 13 : ExecuteQueuedQueriesForAScheme: Finished run on Uri scheme remotebash.
LINTToTTreeLib Stop: 13 : ExecuteQueuedQueriesForAScheme: Finished run on Uri scheme remotebash.
LINTToTTreeLib Stop: 13 : ExecuteQueuedQueriesForAScheme: Finished run on Uri scheme remotebash.
LINTToTTreeLib Start: 30 : LINQToTTree Executor: running 2 queries on gridds://mc15_13tev/mc15_13TeV.304815.MadGraphPythia8EvtGen_A14NNPDF23LO_HSS_LLP_mH600_mS150_lt5m.merge.DAOD_EXOT15.e5102_s2698_r7772_r7676_p2877?preferPlaces=UWTeV-linux,CERNLLP-linux&nFiles=2&jobName=DiVertAnalysis&jobVersion=201
LINTToTTreeLib Start: 30 : LINQToTTree Executor: running 2 queries on gridds://mc15_13tev/mc15_13TeV.304811.MadGraphPythia8EvtGen_A14NNPDF23LO_HSS_LLP_mH400_mS100_lt5m.merge.DAOD_EXOT15.e5102_s2698_r7772_r7676_p2877?preferPlaces=UWTeV-linux,CERNLLP-linux&nFiles=2&jobName=DiVertAnalysis&jobVersion=201
LINTToTTreeLib Start: 30 : LINQToTTree Executor: running 2 queries on gridds://mc15_13tev/mc15_13TeV.304810.MadGraphPythia8EvtGen_A14NNPDF23LO_HSS_LLP_mH400_mS50_lt5m.merge.DAOD_EXOT15.e5102_s2698_r7772_r7676_p2877?preferPlaces=UWTeV-linux,CERNLLP-linux&nFiles=2&jobName=DiVertAnalysis&jobVersion=201
LINTToTTreeLib Start: 13 : ExecuteQueuedQueriesForAScheme: Start run on Uri scheme remotebash, 2 files.
LINTToTTreeLib Start: 13 : ExecuteQueuedQueriesForAScheme: Start run on Uri scheme remotebash, 2 files.
LINTToTTreeLib Start: 13 : ExecuteQueuedQueriesForAScheme: Start run on Uri scheme remotebash, 2 files.
LINTToTTreeLib Stop: 13 : ExecuteQueuedQueriesForAScheme: Finished run on Uri scheme remotebash.
LINTToTTreeLib Stop: 13 : ExecuteQueuedQueriesForAScheme: Finished run on Uri scheme remotebash.
LINTToTTreeLib Stop: 13 : ExecuteQueuedQueriesForAScheme: Finished run on Uri scheme remotebash.
LINTToTTreeLib Stop: 13 : ExecuteQueuedQueriesForAScheme: Finished run on Uri scheme remotebash.
LINTToTTreeLib Stop: 13 : ExecuteQueuedQueriesForAScheme: Finished run on Uri scheme remotebash.
LINTToTTreeLib Stop: 13 : ExecuteQueuedQueriesForAScheme: Finished run on Uri scheme remotebash.
LINTToTTreeLib Stop: 13 : ExecuteQueuedQueriesForAScheme: Finished run on Uri scheme remotebash.
LINTToTTreeLib Stop: 13 : ExecuteQueuedQueriesForAScheme: Finished run on Uri scheme remotebash.
LINTToTTreeLib Stop: 13 : ExecuteQueuedQueriesForAScheme: Finished run on Uri scheme remotebash.
LINTToTTreeLib Stop: 13 : ExecuteQueuedQueriesForAScheme: Finished run on Uri scheme remotebash.
```

**Comment by gordonwatts** [comment]
How do more "finished" get printed than "start"???

**Comment by gordonwatts** [comment]
So in this first case, it runs on 2 files, which should mean it would split things up into two. But it looks like (!?!?!) it splits things up into 4... which makes no sense! :-)

**Comment by gordonwatts** [comment]
And it should be ok - in that the crash should be fine b.c. each is executed in its own directory. So... what the heck? :-)

**Comment by gordonwatts** [comment]
Here is the exception from a run in the wild (log output is above).

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: The process cannot access the file 'C:\Users\gordo\Documents\Code\calratio2017\JetCutStudies\MVADumpTrainingTuples\bin\x86\Debug\signal - files-1700347421-query-2105410456-objs-343055607-crm466987143.csv' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.FileInfo.OpenWrite()
   at Renci.SshNet.ScpClient.InternalDownload(IChannelSession channel, Stream input, FileSystemInfo fileSystemInfo)
   at Renci.SshNet.ScpClient.Download(String filename, FileInfo fileInfo)
   at AtlasSSH.SSHConnection.<>c__DisplayClass29_0.<CopyRemoteFileLocallyAsync>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AtlasSSH.SSHConnection.<CopyRemoteFileLocallyAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AtlasSSH.SSHConnectionTunnel.<CopyRemoteFileLocallyAsync>d__31.MoveNext()

```

**Comment by gordonwatts** [comment]
Ah, this is toCSV, so it is getting copied back not to the local directory, but to the place we are running. Duh.

This might be two bugs:

- We run more batches than we should
- We can't copy the file back and then do the rename without clobbering each other.
