### ISSUE TITLE
See if we can protect copy remote file from failures

### ISSUE THREAD

**Issue by gordonwatts** [gordonwatts/LINQtoROOT#269]
See this crash.
```

07:00:23.840 
07:00:23.841 Unhandled Exception: System.AggregateException: One or more errors occurred. ---> Renci.SshNet.Common.SshOperationTimeoutException: Session operation has timed out
07:00:23.927    at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle, TimeSpan timeout)
07:00:23.927    at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle)
07:00:23.927    at Renci.SshNet.Session.Connect()
07:00:23.927    at Renci.SshNet.BaseClient.Connect()
07:00:23.927    at AtlasSSH.SSHConnection.<>c__DisplayClass1_1.<.ctor>b__1()
07:00:23.927    at System.Lazy`1.CreateValue()
07:00:23.927    at System.Lazy`1.LazyInitValue()
07:00:23.927    at System.Lazy`1.get_Value()
07:00:23.927    at AtlasSSH.SSHConnection.<>c__DisplayClass31_0.<CopyLocalFileRemotelyAsync>b__1()
07:00:23.927    at System.Threading.Tasks.Task.InnerInvoke()
07:00:23.927    at System.Threading.Tasks.Task.Execute()
07:00:23.927 --- End of stack trace from previous location where exception was thrown ---

```

**Comment by gordonwatts** [comment]
And another one:

```
03:46:10.487 Unhandled Exception: System.AggregateException: One or more errors occurred. ---> Renci.SshNet.Common.SshOperationTimeoutException: Session operation has timed out
03:46:10.578    at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle, TimeSpan timeout)
03:46:10.578    at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle)
03:46:10.578    at Renci.SshNet.Session.Connect()
03:46:10.578    at Renci.SshNet.BaseClient.Connect()
03:46:10.578    at AtlasSSH.SSHConnection.<>c__DisplayClass1_1.<.ctor>b__1()
03:46:10.578    at System.Lazy`1.CreateValue()
03:46:10.578    at System.Lazy`1.LazyInitValue()
03:46:10.578    at System.Lazy`1.get_Value()
03:46:10.578    at AtlasSSH.SSHConnection.<>c__DisplayClass31_0.<CopyLocalFileRemotelyAsync>b__1()
03:46:10.578    at System.Threading.Tasks.Task.InnerInvoke()
03:46:10.578    at System.Threading.Tasks.Task.Execute()
03:46:10.578 --- End of stack trace from previous location where exception was thrown ---
03:46:10.578    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
03:46:10.578    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
03:46:10.578    at AtlasSSH.SSHConnection.<CopyLocalFileRemotelyAsync>d__31.MoveNext()
03:46:10.578 --- End of stack trace from previous location where exception was thrown ---
03:46:10.578    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
03:46:10.578    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
03:46:10.578    at AtlasSSH.SSHConnectionTunnel.<CopyLocalFileRemotelyAsync>d__32.MoveNext()
03:46:10.578 --- End of stack trace from previous location where exception was thrown ---

```
