### ISSUE TITLE
Crash trying to open a ROOT File.

### ISSUE THREAD

**Issue by gordonwatts** [gordonwatts/LINQtoROOT#274]
```
9:06:06 Copying slim-runquery.h -> /tmp/JENKINSBUILDDES/Query.c1559401-95eb-49fd-9b51-fa89d73dc234/slim-runquery.h
19:06:06 Copying runquery.h -> /tmp/JENKINSBUILDDES/Query.ba488ea2-e985-400a-8e25-4553e51098ff/runquery.h
19:06:06 System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
19:06:06    at TFile.Open(SByte* , SByte* , SByte* , Int32 , Int32 )
19:06:06    at ROOTNET.NTFile.Open(String name, String option)
19:06:06    at LINQToTTreeLib.ExecutionCommon.CommandLineCommonExecutor.<WriteInputVariablesForTransfer>d__31.MoveNext()
19:06:06    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
19:06:06    at LINQToTTreeLib.ExecutionCommon.CommandLineCommonExecutor.WriteInputVariablesForTransfer(StringBuilder cmds, FileInfo queryResultsFile, IEnumerable`1 varsToTransfer, DirectoryInfo queryDirectory)
19:06:06    at LINQToTTreeLib.ExecutionCommon.CommandLineCommonExecutor.<RunNtupleQuery>d__29.MoveNext()
19:06:06    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
19:06:06    at LINQToTTreeLib.ExecutionCommon.CommandLineCommonExecutor.RunNtupleQuery(StringBuilder cmds, FileInfo queryResultsFile, String selectClass, IEnumerable`1 varsToTransfer, String treeName, Uri[] localFiles, DirectoryInfo queryDirectory)
19:06:06    at LINQToTTreeLib.ExecutionCommon.CommandLineCommonExecutor.<Execute>d__13.MoveNext()
19:06:06    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
19:06:06    at LINQToTTreeLib.ExecutionCommon.CommandLineCommonExecutor.Execute(Uri[] files, FileInfo queryFile, DirectoryInfo queryDirectory, IEnumerable`1 varsToTransfer)
19:06:06    at LINQToTTreeLib.ExecutionCommon.RemoteBashExecutor.<>c__DisplayClass19_0.<<Execute>b__1>d.MoveNext()
19:06:06    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
19:0
```

**Comment by gordonwatts** [comment]
This is probably the same as the Clone issue - which was causing some really bad collisions. That fixed, hopefully this will not reoccur. #275
