### ISSUE TITLE
Better error message when working on a TTree

### ISSUE THREAD

**Issue by gordonwatts** [gordonwatts/LINQtoROOT#282]
This error message:

```
Unhandled Exception: System.ArgumentException: Query must be on a TTree in order to use futures!
   at LINQToTTreeLib.FutureResultOperators.CheckSource[TSource](IQueryable`1 query)
   at LINQToTTreeLib.Files.FileHelperQueryExtensions.FutureAsCSV[T](IQueryable`1 source, FileInfo outputFile, String[] columnHeader)
   at MVADumpTrainingTuples.Program.<WriteOutMJ>d__4.MoveNext() in K:\gwatts\Code\calratio2017\JetCutStudies\MVADumpTrainingTuples\Program.cs:line 172

```

is from this code:

```
                Console.WriteLine("Fetching JZ Sample");
                var backgroundTrainingTree = BuildBackgroundTrainingTreeDataSource(eventsToUseForJzTraining,
                pTCut, Files.NFiles, maxPtCut: TrainingUtils.MaxJetPtForTraining,
                preferPlaces: whereToRun);

                Console.WriteLine("Writing out csv files for multijet.");
                var backgroundTrees = FlattenTrainingTree(await backgroundTrainingTree, outputHistograms, toMakeFlat)
                    .FutureAsCSV(new FileInfo("multijet.csv"));

```

The error message should say something about what it is coming from at the very least

**Comment by gordonwatts** [comment]
The error here is there is a null coming in. So we should have an explicit check for null when future to csv is called to make sure the error is a "proper" one.
