### ISSUE TITLE
Often fails in test build

### ISSUE THREAD

**Issue by gordonwatts** [gordonwatts/LINQtoROOT#44]
Exits for unkown reasons... we get a decent dump from the tc builder, however:

    [22:37:22][Step 4/8] Warning in <TFile::Write>: file C:\TeamCity\buildAgent\work\f961bf02954d6381\gwatts_TCBUILDBOT 2015-12-30 22_37_19\Out\FutureFileWriteWithClose.root not opened in write mode
    [22:37:22][Step 4/8] Passed                LINQToTreeHelpers.Tests.t_FutureTFile.FutureFileWriteWithClose
    [22:37:22][Step 4/8] Passed                LINQToTreeHelpers.Tests.t_FutureUtils.FutureMonadSelectManyWithLet
    [22:37:22][Step 4/8] Passed                LINQToTreeHelpers.Tests.t_FutureUtils.FutureMonadSelectWithLet
    [22:37:22][Step 4/8] Passed                LINQToTreeHelpers.Tests.t_FutureUtils.SelectForOneAsMonad
    [22:37:22][Step 4/8] Passed                LINQToTreeHelpers.Tests.t_FutureUtils.SelectForOneAsMonadNotReady
    [22:37:22][Step 4/8] 
    [22:37:22][Step 4/8] Passed                LINQToTreeHelpers.Tests.t_FutureUtils.SelectManyThreeMonadsNotReady
    [22:37:22][Step 4/8] Passed                LINQToTreeHelpers.Tests.t_FutureUtils.SelectManyTwoMonads
    [22:37:22][Step 4/8] Passed                LINQToTreeHelpers.Tests.t_FutureUtils.SelectManyTwoMonadsNotReady
    [22:37:22][Step 4/8] Passed                LINQToTreeHelpers.Tests.t_FutureUtils.TestAddFutures
    [22:37:22][Step 4/8] Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
    [22:37:22][Step 4/8]    at ROOTNET.NTFile.Write()
    [22:37:22][Step 4/8]    at LINQToTreeHelpers.FutureUtils.FutureTDirectory.Write() in c:\TeamCity\buildAgent\work\f961bf02954d6381\LINQToTTree\LINQToTreeHelpers\FutureUtils\FutureTDirectory.cs:line 136
    [22:37:22][Step 4/8]    at LINQToTreeHelpers.FutureUtils.FutureTFile.Close() in c:\TeamCity\buildAgent\work\f961bf02954d6381\LINQToTTree\LINQToTreeHelpers\FutureUtils\FutureTFile.cs:line 55
    [22:37:22][Step 4/8]    at LINQToTreeHelpers.FutureUtils.FutureTFile.Dispose() in c:\TeamCity\buildAgent\work\f961bf02954d6381\LINQToTTree\LINQToTreeHelpers\FutureUtils\FutureTFile.cs:line 80
    [22:37:22][Step 4/8]    at LINQToTreeHelpers.FutureUtils.FutureTFile.Finalize() in c:\TeamCity\buildAgent\work\f961bf02954d6381\LINQToTTree\LINQToTreeHelpers\FutureUtils\FutureTFile.cs:line 66

This comes from this test:

        [TestMethod]
        public void FutureFileWriteWithClose()
        {
            var f = new FileInfo("FutureFileWriteWithClose.root");
            if (f.Exists)
            {
                f.Delete();
            }

            using (var ftf = new FutureTFile(f))
            {
                ftf.Close();
            }

            f.Refresh();
            Assert.IsTrue(f.Exists);
        }

**Comment by gordonwatts** [comment]
So what could cause that? It works most of the time. A race issue on Windows and the file system? That seems... odd!

**Comment by gordonwatts** [comment]
Here is the code in ROOT:

	Int_t TFile::Write(const char *, Int_t opt, Int_t bufsiz)
	{
	   // Write memory objects to this file.
	   // Loop on all objects in memory (including subdirectories).
	   // A new key is created in the KEYS linked list for each object.
	   // The list of keys is then saved on the file (via WriteKeys)
	   // as a single data record.
	   // For values of opt see TObject::Write().
	   // The directory header info is rewritten on the directory header record.
	   // The linked list of FREE segments is written.
	   // The file header is written (bytes 1->fBEGIN).

	   if (!IsWritable()) {
		  if (!TestBit(kWriteError)) {
			 // Do not print the warning if we already had a SysError.
			 Warning("Write", "file %s not opened in write mode", GetName());
		  }
		  return 0;
	   }

**Comment by gordonwatts** [comment]
So I do a check now in FutureFile - and it is fine after the open. However, I still see the same error (later on). That is... nuts!

**Comment by gordonwatts** [comment]
Ops! Am I reading this wrong - is this error a GC error - note the error occurs in the Dispose and Finalize methods! Hmmm. :(

**Comment by gordonwatts** [comment]
Ok - looking at that dispose code - there were places where it could be called twice, and ti would be a race who called it first, I suppose. Added a little protection in there. That seems to have fixed it running locally. Now we will see if this fix gets it running consistently on the test machine!

**Comment by gordonwatts** [comment]
Ok! The tests passed. Will leave this open for a little while just to make sure that it doesn't reappear (since it was so intermittent).

**Comment by gordonwatts** [comment]
Remains stable! CLose!! :-)
