### ISSUE TITLE
Test out the QueryModel.Clone()

### ISSUE THREAD

**Issue by gordonwatts** [gordonwatts/LINQtoROOT#71]
Do this in the dummy executor - it should always work. It is apparent from the errors I'm seeing with old QM code that this isn't the case. :(

**Comment by gordonwatts** [comment]
Ok - I saw all sorts of crazy crazy crashes when I did this - ones that, actually, didn't make muche sense. So put this off for now, and see what happens as we further develop this framework.

**Comment by gordonwatts** [comment]
Actually, we could put the clone back into the splitter, and then just see what happens, and then take the clone back out again. But I'd rather have it in there for testing.

**Comment by gordonwatts** [comment]
It didn't take long to run into a bug here with Clone. Going to have to actually look at it carefully.

**Comment by gordonwatts** [comment]
Here is the specific bug we are dealing with now:

	Unhandled Exception: System.InvalidOperationException: Query source has already been associated with an expression.
	   at Remotion.Linq.Clauses.QuerySourceMapping.AddMapping(IQuerySource querySource, Expression expression)
	   at Remotion.Linq.Clauses.MainFromClause.Clone(CloneContext cloneContext)
	   at Remotion.Linq.QueryModel.Clone(QuerySourceMapping querySourceMapping)
	   at Remotion.Linq.Clauses.ExpressionTreeVisitors.CloningExpressionTreeVisitor.VisitSubQueryExpression(SubQueryExpression expression)
	   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
	   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitAndConvert[T](T expression, String methodName)
	   at Remotion.Linq.Parsing.ExpressionTreeVisitor.<>c__DisplayClass6`1.<VisitAndConvert>b__5(T expression)
	   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitList[T](ReadOnlyCollection`1 list, Func`2 visitMethod)
	   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitAndConvert[T](ReadOnlyCollection`1 expressions, String callerName)
	   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitNewExpression(NewExpression expression)
	   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
	   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitAndConvert[T](T expression, String methodName)
	   at Remotion.Linq.Parsing.ExpressionTreeVisitor.<>c__DisplayClass6`1.<VisitAndConvert>b__5(T expression)
	   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitList[T](ReadOnlyCollection`1 list, Func`2 visitMethod)
	   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitAndConvert[T](ReadOnlyCollection`1 expressions, String callerName)
	   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitMethodCallExpression(MethodCallExpression expression)
	   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
	   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitLambdaExpression(LambdaExpression expression)
	   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
	   at Remotion.Linq.Clauses.ExpressionTreeVisitors.CloningExpressionTreeVisitor.AdjustExpressionAfterCloning(Expression expression, QuerySourceMapping querySourceMapping)
	   at Remotion.Linq.QueryModel.<>c__DisplayClass7.<Clone>b__6(Expression ex)
	   at Remotion.Linq.Clauses.ResultOperators.AggregateFromSeedResultOperator.TransformExpressions(Func`2 transformation)
	   at Remotion.Linq.QueryModel.TransformExpressions(Func`2 transformation)
	   at Remotion.Linq.QueryModel.Clone(QuerySourceMapping querySourceMapping)
	   at LINQToTTreeLib.QueryVisitors.ConcatSplitterQueryVisitor.SplitFromClauses.VisitMainFromClause(MainFromClause fromClause, QueryModel queryModel)
	   at Remotion.Linq.Clauses.MainFromClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
	   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
	   at LINQToTTreeLib.QueryVisitors.ConcatSplitterQueryVisitor.Split(QueryModel source)
	   at LINQToTTreeLib.TTreeQueryExecutor.ExecuteScalarConcatQM[TResult](QueryModel queryModel)
	   at LINQToTTreeLib.TTreeQueryExecutor.ExecuteScalarAsFuture[TResult](QueryModel queryModel)
	   at LINQToTTreeLib.FutureResultOperators.FutureExecuteScalarHelper[TSource,TResult](QueriableTTree`1 q, MethodCallExpression expr)
	   at LINQToTTreeLib.FutureResultOperators.FutureAggregate[TSource,TAccumulate](IQueryable`1 source, TAccumulate seed, Expression`1 func)
	   at LINQToTTreeLib.Helpers.FutureApplyToObject[TSource,TResult](IQueryable`1 source, TResult seed, Expression`1 apply)
	   at LINQToTreeHelpers.Plotting.FuturePlot[TSource](IQueryable`1 source, String plotName, String plotTitle, Int32 nbins, Double lowBin, Double highBin, Expression`1 xValue, Expression`1 weight)
	   at LINQToTreeHelpers.PlottingUtils.PlotSpec1D`1.MakeFuturePlot(String nameString, String titleString, IQueryable`1 goodEvents)
	   at LINQToTreeHelpers.PlottingUtils.FuturePlot[T](IQueryable`1 source, String name, String title, IPlotSpec`1 plotSpecification, String[] nameAndTitleFormatArgs)
	   at LINQToTreeHelpers.PlottingUtils.FuturePlot[T](IQueryable`1 source, IPlotSpec`1 plotSpecification, String[] nameAndTitleFormatArgs)
	   at JZPlotter.Program.Main(String[] args) in C:\Users\gordo\Documents\Code\calratio2015\JetCutStudies\JZPlotter\Program.cs:line 49

**Comment by gordonwatts** [comment]
And here is a dump of the QM that is causing that problem:

    (LINQToTTreeLib.Tests.QMExtractorQueriable`1[LINQToTTreeLib.TTreeQueryExecutorTest+TestNtupeArrD]) select 1 => Aggregate(0, acc => (acc + Convert(1)))
